### ISSUE TITLE
Some Abilities self-organize on page, others scroll off page

### ISSUE THREAD

**Issue by Merhotep** [PeteAUK/warscroll-designer#20]
There is space under the description, but sometimes an ability added just starts a new column off-screen making the scroll unprintable on 1 page.  I haven’t id3ntified the pattern yet; sorry!

**Comment by PeteAUK** [comment]
Hi, could you fill out a bit more information as per the template please, including a few screenshots?  Not come across this in the development process yet so need a bit of direction with where to look to resolve.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Comment by Merhotep** [comment]
Pete,

Not sure this is a true bug, if my total text could not quite be made to
fit,after all.  I discovered the function to select page style, and by
increasing to next size up, everything is successfully inserted.
Thanks.

**Comment by PeteAUK** [comment]
This sounds like it may be related to the text flow that comes from the CSS "columns" property.  Rather than trying to write my own column wrapping routine (which is notoriously difficult due to font-width etc), I'm using a browser based solution.  However it is exceptionally fickle at times.

Glad the page style has resolved this.
